### ISSUE TITLE
210309 설탕 배달, 큰 수 A+B

### ISSUE THREAD

**Issue by devejs** [coding-mates/Algorithm_v2#10]
설탕 배달  
https://www.acmicpc.net/problem/2839  
큰 수 A+B  
https://www.acmicpc.net/problem/10757

**Comment by JHYOOOOON** [comment]
[설탕 배달]
5을 0개부터 개수를 늘려가며 빼면서 남은 값을 3으로 나눴을 때의 최소 개수를 출력

[큰 수 A+B]
수가 너무 크기 때문에 string으로 받아서 계산해 출력

**Comment by devejs** [comment]
두번째 문제인 큰 수 A+B(10757)은 파이썬으로는 너무 짧아서 코멘트에 첨부합니다.
```Python
a,b = map(int,input().split())
print(a+b)
```
