### ISSUE TITLE
210303 크로아티아 알파벳, 그룹 단어 체커

### ISSUE THREAD

**Issue by JHYOOOOON** [coding-mates/Algorithm_v2#5]
- 크로아티아 알파벳
https://www.acmicpc.net/problem/2941
- 그룹 단어 체커
https://www.acmicpc.net/problem/1316

**Comment by devejs** [comment]
#4에 포함시켜 커밋했습니다.
- 크로아티아 알파벳 https://github.com/coding-mates/Algorithm_v2/blob/main/Eunjee/Baekjoon%202941%20Python.py
- 그룹 단어 체커 https://github.com/coding-mates/Algorithm_v2/blob/main/Eunjee/Baekjoon%201316%20Python.py
